model_name: 'UNext'
batch_size: 64
num_workers: 0
num_classes: 1
deep_supervision: false
input_channels: 3
optimizer: 'Adam'
learning_rate: 0.001
weight_decay: 0.0001
momentum: 0.9
scheduler: 'CosineAnnealingLR'
epochs: 100
min_learning_rate: 1e-5
scheduler_factor: 0.1
scheduler_patience: 2
scheduler_milestones: '1,2'
scheduler_gamma: 0.6667
data_path: 'D:/Projects/UNeXt/datasets/busi'
output_path: 'D:/Projects/UNeXt/output/'
early_stopping: -1
input_w: 256
input_h: 256
transform_flip_probability: 0.5